[keys.right-little]
short_name = 'rl'

[keys.right-ring]
short_name = 'rr'

[keys.right-middle]
short_name = 'rm'

[keys.right-first]
short_name = 'rf'

[keys.left-ring]
short_name = 'lr'

[keys.left-middle]
short_name = 'lm'

[keys.left-first]
short_name = 'lf'

[keys.left-thumb]
short_name = 'lt'

[keys.right-little-half]
short_name = 'rl-'
description = 'Slide the right little finger back to only close the large hole'

[keys.right-ring-half]
short_name = 'rr-'
description = 'Slide the right ring finger back to only close the large hole'

[keys.octave]
short_name = 'oct'
description = 'Half-cover the thumb hole with the nail'

[keys.close-bell]
short_name = 'cb'
description = 'Partly cover the bell of the instrument with the knee'

fingerings = [
    'rl  rr  rm  rf  lr  lm  lf  lt ',  # C5 on soprano
    'rl- rr  rm  rf  lr  lm  lf  lt ',  # C#5
    '    rr  rm  rf  lr  lm  lf     ',  # D5
    '    rr- rm  rf  lr  lm  lf  lt ',  # D#5
    '        rm  rf  lr  lm  lf     ',  # E5
    'rl  rr      rf  lr  lm  lf     ',  # F5
    '    rr  rm      lr  lm  lf  lt ',  # F#5
    '                lr  lm  lf     ',  # G5
    '    rr- rm  rf      lm  lf  lt ',  # G#5
    '                    lm  lf     ',  # A5
    '            rf      lm  lf  lt ',  # A#5
    '                        lf     ',  # B5
    '                    lm  lt     ',  # C6
    '                    lm  lf     ',  # C#6
    '                    lm         ',  # D6
    '    rr  rm  rf  lr  lm         ',  # D#6
    '        rm  rf  lr  lm  lf  oct',  # E6
    '    rr      rf  lr  lm  lf  oct',  # F6
    '        rm      lr  lm  lf  oct',  # F#6
    '                lr  lm  lf  oct',  # G6
    '            rf      lm  lf  oct',  # G#6
    '                    lm  lf  oct',  # A6
    'rl- rr  rm          lm  lf  oct',  # A#6
    '        rm  rf      lm  lf  oct',  # B6
    '        rm  rf          lf  oct',  # C7
    'rl  rr      rf   lr     lf  oct cb',  # C#7
    'rl  rr      rf   lr     lf  oct',  # D7
]



[fingerings]
C1 = ' rl  rr  rm  rf  lr  lm  lf  lt '
Db1 = 'rl- rr  rm  rf  lr  lm  lf  lt '
D1 = '     rr  rm  rf  lr  lm  lf     '
Eb1 = '    rr- rm  rf  lr  lm  lf  lt '
E1 = '         rm  rf  lr  lm  lf     '
F1 = ' rl  rr      rf  lr  lm  lf     '
Gb1 = '    rr  rm      lr  lm  lf  lt '
G1 = '                 lr  lm  lf     '
Ab1 = '    rr- rm  rf      lm  lf  lt '
A1 = '                     lm  lf     '
Bb1 = '            rf      lm  lf  lt '
B1 = '                         lf     '
C2 = '                     lm  lt     '
Db2 = '                    lm  lf     '
D2 = '                     lm         '
Eb2 = '    rr  rm  rf  lr  lm         '
E2 = '         rm  rf  lr  lm  lf  oct'
F2 = '     rr      rf  lr  lm  lf  oct'
Gb2 = '        rm      lr  lm  lf  oct'
G2 = '                 lr  lm  lf  oct'
Ab2 = '            rf      lm  lf  oct'
A2 = '                     lm  lf  oct'
Bb2 = 'rl- rr  rm          lm  lf  oct'
B2 = '         rm  rf      lm  lf  oct'
C3 = '         rm  rf          lf  oct'
Db3 = 'rl  rr      rf   lr     lf  oct cb'
D3 =  'rl  rr      rf   lr     lf  oct'


fingerings = [
    'R4  R3  R2  R1  L3  L2  L1  Lt ',  # C1
    'R4- R3  R2  R1  L3  L2  L1  Lt ',  # C#1
    '    R3  R2  R1  L3  L2  L1     ',  # D1
    '    RR- R2  R1  L3  L2  L1  Lt ',  # D#1
    '        R2  R1  L3  L2  L1     ',  # E1
    'R4  R3      R1  L3  L2  L1     ',  # F1
    '    R3  R2      L3  L2  L1  Lt ',  # F#1
    '                L3  L2  L1     ',  # G1
    '    RR- R2  R1      L2  L1  Lt ',  # G#1
    '                    L2  L1     ',  # A1
    '            R1      L2  L1  Lt ',  # A#1
    '                        L1     ',  # B1
    '                    L2  Lt     ',  # C2
    '                    L2  L1     ',  # C#2
    '                    L2         ',  # D2
    '    R3  R2  R1  L3  L2         ',  # D#2
    '        R2  R1  L3  L2  L1  oct',  # E2
    '    R3      R1  L3  L2  L1  oct',  # F2
    '        R2      L3  L2  L1  oct',  # F#2
    '                L3  L2  L1  oct',  # G2
    '            R1      L2  L1  oct',  # G#2
    '                    L2  L1  oct',  # A2
    'R4- R3  R2          L2  L1  oct',  # A#2
    '        R2  R1      L2  L1  oct',  # B2
    '        R2  R1          L1  oct',  # C3
    'R4  R3      R1   L3     L1  oct cb',  # C#3
    'R4- R3      R1   L3     L1  oct',  # C#3
]
