unique-fingering = true
base_note = C

[keys.right-little]
short_name = 'rl'

[keys.right-ring]
short_name = 'rr'

[keys.right-middle]
short_name = 'rm'
lift = {'C1': 'F1'}

[keys.right-first]
short_name = 'rf'
lift = {'D1': 'F#1'}

[keys.left-little]
short_name = 'll'

[keys.left-ring]
short_name = 'lr'

[keys.left-middle]
short_name = 'lm'
lift = {'F1': 'Bb1'}

[keys.left-first]
short_name = 'lf'

[keys.left-thumb]
short_name = 'lt'

[keys.right-little-half]
short_name = 'rlh'
description = 'Slide the right little finger back to reveal the small hole'
modifies = {'C1': 1}

[keys.right-ring-half]
short_name = 'rrh'
description = 'Slide the right ring finger back to reveal the small hole'
modifies = {'D1': 1}

[keys.octave]
short_name = 'oct'
description = 'Half-cover the thumb hole with the nail'
modifies = {'E1': 'E2', 'G1': 'G2', 'A1': 'A2'}

[keys.close-bell]
short_name = 'cb'
description = 'Partly cover the bell of the instrument with the knee'




main = ['rl', 'rr', 'rm', 'rf', 'll', 'lr', 'lm', 'lf', 'lt']
