[instrument-lowest-c]

contrabass = 'Eb1'
bass = 'Bb1'
baritone = 'Eb2'
tenor = 'Bb2'
c-melody = 'C3'
alto = 'Eb3'
soprano = 'Bb3'
sopranino = 'Eb3'
sopranissimo = 'Bb4'


# See https://www.wfg.woodwind.org/sax/sax_fing.html

# Left hand

[key.'Octave']
description = 'Octave'
short_name = 'oct'
press = 'left thumb'
range = {lower = 'D2', upper = 'Db3'}

[key.'Palm Eb']
description = 'Palm Eb key'
short_name = 'peb'
press = 'left palm'

[key.'Palm D']
description = 'Palm D key'
short_name = 'pd'
press = 'left palm'

[key.'Palm F']
description = 'Palm F key'
short_name = 'pf'
press = 'left palm'

[key.'Front F']
description = 'Front f key'
short_name = 'ff'
press = 'left 1'

[key.'1 left']
description = 'First left finger key'
short_name = '1L'
press = 'left 1'

[key.'Bb bis']
description = 'Bb bis key'
short_name = 'bbb'
press = 'left 2'

[key.'2 left']
description = 'Second left finger key'
short_name = '2L'
press = 'left 2'

[key.'3 left']
description = 'Third left finger key'
short_name = '3L'
press = 'left 3'

[key.'G#']
description = 'G# key'
short_name = 'gs'
press = 'left 4'

[key.'C#']
description = 'C# key'
short_name = 'cs'
press = 'left palm'

[key.'Low B']
description = 'Low B key'
short_name = 'lb'
press = 'left 4'

[key.'Low Bb']
description = 'Low Bb key'
short_name = 'lbb'
press = 'left 4'

# Right hand keys

[key.'Side E']
description = 'Side E key'
short_name = 'se'
press = 'right side key'

[key.'Side C']
description = 'Side C key'
short_name = 'sc'
press = 'right side key'

[key.'Side Bb']
description = 'Side Bb key'
short_name = 'sbb'
press = 'right side key'

[key.'1 right']
description = 'First right finger key'
short_name = '1R'
press = 'right 1'

[key.'High# F']
description = 'High F# key'
short_name = 'hfs'
press = 'right 2'

[key.'2 right']
description = 'Second right finger key'
short_name = '2R'
press = 'right 2'

[key.'Alt F#']
description = 'Alternate F# key'
short_name = 'afs'
press = 'right 3'

[key.'3 right']
description = 'Third right Finger key'
short_name = '3R'
press = 'right 3'

[key.'Low Eb']
description = 'Low Eb key'
short_name = 'leb'
press = 'right 4'

[key.'Low C']
description = 'Low C key'
short_name = 'lc'
press = 'right 4'

[key.'Low A']
description = 'Low A key'
short_name = 'la'
press = 'left thumb'
only_on = ['baritone']


[fingerings]
# Only alternative fingerings for D2 through Db3 because of the octave key

ALL = 'oct peb pd  pf  ff  1L  bbb 2L  3L  gs  cs  lb  lbb se  sc  sbb 1R  hfs 2R  afs 3R  leb lc  la  '

A_0 = '                    1L      2L  3L          lb  lbb             1R      2R      3R      lc  la  '
Bb0 = '                    1L      2L  3L          lb  lbb             1R      2R      3R      lc      '
B_0 = '                    1L      2L  3L          lb                  1R      2R      3R      lc      '
C_1 = '                    1L      2L  3L                              1R      2R      3R      lc      '
Db1 = '                    1L      2L  3L      cs                      1R      2R      3R      lc      '
D_1 = '                    1L      2L  3L                              1R      2R      3R              '
Eb1 = '                    1L      2L  3L                              1R      2R      3R  leb         '
E_1 = '                    1L      2L  3L                              1R      2R                      '
F_1 = '                    1L      2L  3L                              1R                              '
Gb1 = '                    1L      2L  3L                                      2R                      '
G_1 = '                    1L      2L  3L                                                              '
Ab1 = '                    1L      2L  3L  gs                                                          '
A_1 = '                    1L      2L                                                                  '
Bb1 = '                    1L  bbb 2L                              sbb                                 '
B_1 = '                    1L                                                                          '
C_2 = '                            2L                                                                  '
Db2 = '                                                                                                '
