The standard modern saxophone has 23 keys.

The upper section (left hand position) has access to five padded keys, three palm keys, four pinky keys and the octave key.

The right hand has access to three padded keys, two pinky keys and five palm keys which includes the altissimo high F# key.


https://www.wfg.woodwind.org/sax/sax_fing.html#a:


Left:
    T Eb D F f 1 Bb 2 3 G# C# B Bb
Right:
    E C Bb 1 f# 2 F# 3 Eb C"


LEFT
T: Octave
Eb: Eb palm key
D: D palm key
F: F palm key
f: Front f key
1L: First finger key left
Bb: Bb bis key
2L: Second finger key left
3L: Third Finger key left
G#: G# palm key
C#: C# palm key
B: Low B key
Bb Low Bb key

RIGHT

E: E side key
C: C side key
Bb: Bb side key
1R: First finger key right
f#: High F# key
2R: Second finger key right
F#: Alternate F# key
3R: Third Finger key right
Eb: Low Eb key
C: Low C key






Trevor: James Saxophone key chart


# 1 - octave
Octave thumb key

Front F key
B key
Bb bis key
A key
G key
G# key


# 3 Left hand palm keys

Top F key
Top D# key
Top D key


# 4 Left hand table keys

G# lever
Low B lever
Low C# lever
Low Bb lever


X Side C key
X Side Bb key
X? F# key

X Top F# key)

X Top E key)

#

# Left hand table keys

F key Side Bb lever E key and touchpiece Top F# lever Side F# key D key and touchpiece
Low Eb / D# key Low C key Body / Bow brace
Low C key Low C key guard

Bell
Top E lever Side C lever Low Bb key Low B / Bb key guard Low B key Low C# key Bow
Worldwind House, Ashmill Park, Ashford Road, Lenham, Kent, ME17 2GQ
T: 01622-859590 E: tjj@worldwind.co.uk www.trevorjames.com
