[instrument-lowest-c]

contrabass = 'Eb1'
bass = 'Bb1'
baritone = 'Eb2'
tenor = 'Bb2'
c-melody = 'C3'
alto = 'Eb3'
soprano = 'Bb3'
sopranino = 'Eb3'
sopranissimo = 'Bb4'


# See https://www.wfg.woodwind.org/sax/sax_fing.html

# Left hand

[keys.'Octave']
description = 'Octave'
short_name = 'oct'
press = 'left thumb'

[keys.'Palm Eb']
description = 'Palm Eb key'
short_name = 'peb'
press = 'left palm'

[keys.'Palm D']
description = 'Palm D key'
short_name = 'pd'
press = 'left palm'

[keys.'Palm F']
description = 'Palm F key'
short_name = 'pf'
press = 'left palm'

[keys.'Front F']
description = 'Front f key'
short_name = 'ff'
press = 'left 1'

[keys.'1 left']
description = 'First left finger key'
short_name = '1L'
press = 'left 1'

[keys.'Bb bis']
description = 'Bb bis key'
short_name = 'bbb'
press = 'left 2'

[keys.'2 left']
description = 'Second left finger key'
short_name = '2L'
press = 'left 2'

[keys.'3 left']
description = 'Third left finger key'
short_name = '3L'
press = 'left 3'

[keys.'G#']
description = 'G# key'
short_name = 'gs'
press = 'left 4'

[keys.'C#']
description = 'C# key'
short_name = 'cs'
press = 'left palm'

[keys.'Low B']
description = 'Low B key'
short_name = 'lb'
press = 'left 4'

[keys.'Low Bb']
description = 'Low Bb key'
short_name = 'lbb'
press = 'left 4'

# Right hand keys

[keys.'Side E']
description = 'Side E key'
short_name = 'se'
press = 'right side key'

[keys.'Side C']
description = 'Side C key'
short_name = 'sc'
press = 'right side key'

[keys.'Side Bb']
description = 'Side Bb key'
short_name = 'sbb'
press = 'right side key'

[keys.'1 right']
description = 'First right finger key'
short_name = '1R'
press = 'right 1'

[keys.'High# F']
description = 'High F# key'
short_name = 'hfs'
press = 'right 2'

[keys.'2 right']
description = 'Second right finger key'
short_name = '2R'
press = 'right 2'

[keys.'Alt F#']
description = 'Alternate F# key'
short_name = 'afs'
press = 'right 3'

[keys.'3 right']
description = 'Third right Finger key'
short_name = '3R'
press = 'right 3'

[keys.'Low Eb']
description = 'Low Eb key'
short_name = 'leb'
press = 'right 4'

[keys.'Low C']
description = 'Low C key'
short_name = 'lc'
press = 'right 4'

[keys.'Low A']
description = 'Low A key'
short_name = 'la'
press = 'left thumb'
only_on = ['baritone']


[fingerings]
# Only alternative fingerings for D2 through Db3 because of the octave key

ALL = 'oct peb pd  pf  ff  1L  bbb 2L  3L  gs  cs  lb  lbb se  sc  sbb 1R  hfs 2R  afs 3R  leb lc  la  '

A_0 = '                    1L      2L  3L          lb  lbb             1R      2R      3R      lc  la  '
Bb0 = '                    1L      2L  3L          lb  lbb             1R      2R      3R      lc      '
B_0 = '                    1L      2L  3L          lb                  1R      2R      3R      lc      '
C_1 = '                    1L      2L  3L                              1R      2R      3R      lc      '
Db1 = '                    1L      2L  3L      cs                      1R      2R      3R      lc      '
D_1 = '                    1L      2L  3L                              1R      2R      3R              '
Eb1 = '                    1L      2L  3L                              1R      2R      3R  leb         '
E_1 = '                    1L      2L  3L                              1R      2R                      '
F_1 = '                    1L      2L  3L                              1R                              '
Gb1 = '                    1L      2L  3L                                      2R                      '
G_1 = '                    1L      2L  3L                                                              '
Ab1 = '                    1L      2L  3L  gs                                                          '
A_1 = '                    1L      2L                                                                  '
Bb1 = '                    1L  bbb 2L                              sbb                                 '
B_1 = '                    1L                                                                          '
C_2 = '                            2L                                                                  '
Db2 = '                                                                                                '
D_2 = 'oct                 1L      2L  3L                              1R      2R      3R              '
Eb2 = 'oct                 1L      2L  3L                              1R      2R      3R  leb         '
E_2 = 'oct                 1L      2L  3L                              1R      2R                      '
F_2 = 'oct                 1L      2L  3L                              1R                              '
Gb2 = 'oct                 1L      2L  3L                                      2R                      '
G_2 = 'oct                 1L      2L  3L                                                              '
Ab2 = 'oct                 1L      2L  3L  gs                                                          '
A_2 = 'oct                 1L      2L                                                                  '
Bb2 = 'oct                 1L  bbb 2L                              sbb                                 '
B_2 = 'oct                 1L                                                                          '
C_3 = 'oct                         2L                                                                  '
Db3 = 'oct                                                                                             '
