[key.'Octave']
description = 'Octave'
short_name = 'oc'
presser = 'left thumb'

[key.'Eb palm']
description = 'Eb palm key'
short_name = 'eb'
presser = 'left palm'

[key.'D palm']
description = 'D palm key'
short_name = 'dp'
presser = 'left palm'

[key.'F palm']
description = 'F palm key'
short_name = 'fp'
presser = 'left palm'

[key.'F front']
description = 'Front f key'
short_name = 'ff'
presser = 'left 1'

[key.'1 left']
description = 'First left finger key'
short_name = '1L'
presser = 'left 1'

[key.'Bb bis']
description = 'Bb bis key'
short_name = 'bb'
presser = 'left 2'

[key.'2 left']
description = 'Second left finger key'
short_name = '2L'
presser = 'left 2'

[key.'3 left']
description = 'Third left finger key'
short_name = '3L'
presser = 'left 3'

[key.'G# palm']
description = 'G# palm key'
short_name = 'gp'
presser = 'left palm'

[key.'C# palm']
description = 'C# palm key'
short_name = 'cp'
presser = 'left palm'

[key.'B low']
description = 'Low B key'
short_name = 'lb'
presser = 'left 4'

[key.'Bb low']
description = 'Low Bb key'
short_name = 'lf'
presser = 'left 4'

# Right hand keys

[key.'E side']
description = 'E side key'
short_name = 'es'
presser = 'right side key'

[key.'C side']
description = 'C side key'
short_name = 'cs'
presser = 'right side key'

[key.'Bb side']
description = 'Bb side key'
short_name = 'bs'
presser = 'right side key'

[key.'1 right']
description = 'First right finger key'
short_name = '1r'
presser = 'right 1'

[key.'F# high']
description = 'High F# key'
short_name = 'fh'
presser = 'right 2'

[key.'2 right']
description = 'Second right finger key'
short_name = '2r'
presser = 'right 2'

[key.'F# alt']
description = 'Alternate F# key'
short_name = 'af'
presser = 'right 3'

[key.'3 right']
description = 'Third right Finger key'
short_name = '3r'
presser = 'right 3'

[key.'Eb low']
description = 'Low Eb key'
short_name = 'le'
presser = 'right 4'

[key.'C low']
description = 'Low C key'
short_name = 'lc'
presser = 'right 4'
