[layout]
spacing = 120
width = 100
style = """
.outline { fill: white; stroke: black; stroke-width: 1; }
.caption { font-size: 60 }
"""

[layout.defs]

pad = '<circle cx="50" cy="50" r="50" />'
little = '<circle cx="80" cy="55" r="20" />'
big = '<circle cx="30" cy="30" r="30" />'

octave-cover = '<rect x="-25" y="0" width="50" height="50" style="fill: green;"/>'
separator = '<rect x="0" y="50" width="120" height="1" style="fill: black;"/>'

[layout.pieces.left-thumb.parts]
_off = 'pad @ outline'
oct = 'pad + octave-cover'
left-thumb = 'pad'

[layout.pieces._separator-1.parts]
_off = 'separator'

[layout.pieces.left-1.parts]
_off = 'pad @ outline'
left-1 = 'pad'

[layout.pieces.left-2.parts]
_off = 'pad @ outline'
left-2 = 'pad'

[layout.pieces.left-3.parts]
_off = 'pad @ outline'
left-3 = 'pad'

[layout.pieces._separator-2.parts]
_off = 'separator'

[layout.pieces.right-1.parts]
_off = 'pad @ outline'
right-1 = 'pad'

[layout.pieces.right-2.parts]
_off = 'pad @ outline'
right-2 = 'pad'

[layout.pieces.right-3.parts]
_off = 'little @ outline + big @ outline'
right-3 = 'little + big'
right-3-half = 'little @ outline + big'

[layout.pieces.right-4.parts]
_off = 'little @ outline + big @ outline'
right-4 = 'little + big'
right-4-half = 'little @ outline + big'
