# Left hand keys

[metadata]
author = 'Tom Ritchford (tom@swirly.com)'
version = 'v0.1.0'
name = 'Baroque fingering system for the recorder'
tags = ['recorder', 'baroque']

[keys.left-thumb]
short_name = 'lt'
press = "left-thumb"

[keys.octave]
short_name = 'oct'
press = "left-thumb"
description = 'Half-cover the thumb hole with the nail'

[keys.left-1]
short_name = 'l1'
press = "left-1"

[keys.left-2]
short_name = 'l2'
press = "left-2"

[keys.left-3]
short_name = 'l3'
press = "left-3"

# Right-hand keys

[keys.right-1]
short_name = 'r1'
press = "right-1"

[keys.right-2]
short_name = 'r2'
press = "right-2"

[keys.right-3]
short_name = 'r3'
press = "right-3"

[keys.right-3-half]
short_name = 'r3h'
press = "right-3"
description = 'Slide the right ring finger back to only close the large hole'

[keys.right-4]
short_name = 'r4'
press = "right-4"

[keys.right-4-half]
short_name = 'r4h'
press = "right-4"
description = 'Slide the right little finger back to only close the large hole'

# The bell

[keys.cover-bell]
short_name = 'cb'
press = 'knee'
description = 'Partly cover the bell of the instrument with the knee'

[fingerings]
all = 'oct lt  l1  l2  l3  r1  r2  r3  r3h r4  r4h cb  '
C_1 = '    lt  l1  l2  l3  r1  r2  r3      r4          '
Db1 = '    lt  l1  l2  l3  r1  r2  r3          r4h     '
D_1 = '    lt  l1  l2  l3  r1  r2  r3                  '
Eb1 = '    lt  l1  l2  l3  r1  r2      r3h             '
E_1 = '    lt  l1  l2  l3  r1  r2                      '
F_1 = '    lt  l1  l2  l3  r1      r3      r3          '
Gb1 = '    lt  l1  l2  l3      r2  r3                  '
G_1 = '    lt  l1  l2  l3                              '
Ab1 = '    lt  l1  l2      r1  r2      r3h             '
A_1 = '    lt  l1  l2                                  '
Bb1 = '    lt  l1  l2      r1                          '
B_1 = '    lt  l1                                      '
C_2 = '    lt      l2                                  '
Db2 = '        l1  l2                                  '
D_2 = '            l2                                  '
Eb2 = '            l2  l3  r1  r2  r3                  '
E_2 = 'oct     l1  l2  l3  r1  r2                      '
F_2 = 'oct     l1  l2  l3  r1      r3                  '
Gb2 = 'oct     l1  l2  l3      r2                      '
G_2 = 'oct     l1  l2  l3                              '
Ab2 = 'oct     l1  l2      r1                          '
A_2 = 'oct     l1  l2                                  '
Bb2 = 'oct     l1  l2          r2  r3                  ' # CHECK THIS
B_2 = 'oct     l1  l2      r1  r2                      '
C_3 = 'oct     l1          r1  r2                      '
Db3 = 'oct     l1      l3  r1      r3      r3      cb  '
D_3 = 'oct     l1      l3  r1      r3      r3          '

[lowest_c]

# From https://www.rochars.org/recorder-freqency-ranges
contrabass = 'F2'
great-bass = 'C3'
bass = 'F3'
tenor = 'C4'
alto = 'F4'
soprano = 'C5'
sopranino = 'F5'
garklein = 'C6'
