# Left hand keys

[metadata]
author = 'Tom Ritchford (tom@swirly.com)'
version = 'v0.1.0'
name = 'Baroque fingering system for the recorder'
tags = ['recorder', 'baroque']

[keys."left thumb"]
short_name = 'lt'
press = "left thumb"

[keys.octave]
short_name = 'oct'
press = "left thumb"
description = 'Half-cover the thumb hole with the nail'

[keys."left first finger"]
short_name = 'lf'
press = "left 1"

[keys."left middle finger"]
short_name = 'lm'
press = "left 2"

[keys."left ring finger"]
short_name = 'lr'
press = "left 3"

# Right-hand keys

[keys."right first finger"]
short_name = 'rf'
press = "right 1"

[keys."right middle finger"]
short_name = 'rm'
press = "right 2"

[keys."right ring finger"]
short_name = 'rr'
press = "right 3"

[keys."right ring finger half"]
short_name = 'rrh'
press = "right 3"
description = 'Slide the right ring finger back to only close the large hole'

[keys."right little finger"]
short_name = 'rl'
press = "right 4"

[keys."right little finger half"]
short_name = 'rlh'
press = "right 4"
description = 'Slide the right little finger back to only close the large hole'

# The bell

[keys.close-bell]
short_name = 'cb'
press = 'knee'
description = 'Partly cover the bell of the instrument with the knee'


[fingerings]
all = 'oct lt  lf  lm  lr  rf  rm  rr  rrh rl  rlh cb  '
C_1 = '    lt  lf  lm  lr  rf  rm  rr      rl          '
Db1 = '    lt  lf  lm  lr  rf  rm  rr          rlh     '
D_1 = '    lt  lf  lm  lr  rf  rm  rr                  '
Eb1 = '    lt  lf  lm  lr  rf  rm      rrh             '
E_1 = '    lt  lf  lm  lr  rf  rm                      '
F_1 = '    lt  lf  lm  lr  rf      rr      rl          '
Gb1 = '    lt  lf  lm  lr      rm  rr                  '
G_1 = '    lt  lf  lm  lr                              '
Ab1 = '    lt  lf  lm      rf  rm      rrh             '
A_1 = '    lt  lf  lm                                  '
Bb1 = '    lt  lf  lm      rf                          '
B_1 = '    lt  lf                                      '
C_2 = '    lt  lt  lm                                  '
Db2 = '        lf  lm                                  '
D_2 = '            lm                                  '
Eb2 = '            lm  lr  rf  rm  rr                  '
E_2 = 'oct     lf  lm  lr  rf  rm                      '
F_2 = 'oct     lf  lm  lr  rf      rr                  '
Gb2 = 'oct     lf  lm  lr      rm                      '
G_2 = 'oct     lf  lm  lr                              '
Ab2 = 'oct     lf  lm      rf                          '
A_2 = 'oct     lf  lm                                  '
Bb2 = 'oct     lf  lm          rm  rr  rm              '
B_2 = 'oct     lf  lm      rf  rm                      '
C_3 = 'oct     lf          rf  rm                      '
Db3 = 'oct     lf      lr  rf      rr      rl      cb  '
D_3 = 'oct     lf      lr  rf      rr      rl          '

[lowest_c]

# From https://www.rochars.org/recorder-freqency-ranges
contrabass = 'F2'
great-bass = 'C3'
bass = 'F3'
tenor = 'C4'
alto = 'F4'
soprano = 'C5'
sopranino = 'F5'
garklein = 'C6'
